#!/usr/bin/env python
import sys
try:
    from PIL import Image ,ImageOps ,ImageDraw
except ImportError:
    print("Please install Pillow from: https://pypi.python.org/pypi/Pillow/3.0.0")
    sys.exit(1)

import os ,sys 
imgpath=""
if len(sys.argv) != 1:
    print("Usage %s <image>" % sys.argv[0])
    exit(1)
if sys.argv[0] == "":
    print ("enter file full path")
    exit(1)
else:
    imgpath=str(sys.argv[0])

img = Image.open(imgpath)
d1 = Image.open('./1.png')
d2= Image.open('./2.png')
d3 = Image.open('./3.png')
d4 = Image.open('./4.png')
d5 = Image.open('./5.png')
d6 = Image.open('./6.png')

img = ImageOps.grayscale(img)
img = ImageOps.equalize(img)
img=img.resize((img.width*10,img.height*10))
img.save("./pngconvert","JPEG")
dicew =300
dicesize = int(img.width*1.0/dicew)
print(dicesize)
diceh = int(img.height*1.0/img.width*dicew)

nim = Image.new("L",(img.width,img.height),'white')
nimdd = Image.new("L",(img.width,img.height),'white')
nimd = ImageDraw.Draw(nim)

dices= [d1,d2,d3,d4,d5,d6]
for i in range(0,len(dices)):
    dices[i]=dices[i].resize((dicesize,dicesize))
    dices[i].save("./"+str(i)+"temp.jpg","JPEG")

print(img.width,img.height)
total=0
for y in range(0,img.height-dicesize,dicesize):
    for x in range(0,img.width-dicesize,dicesize):
        thisSectorColor = 0
        for dicex in range(0,dicesize):
            for dicey in range(0,dicesize):
                thisColor = img.getpixel((x+dicex,y+dicey))
                thisSectorColor+=thisColor
        thisSectorColor/=(dicesize**2)
        diceNumber = int((255-thisSectorColor)*6.0/255+1)
        box=(x,y,x+dicesize,y+dicesize)
        if diceNumber==1:
            nimdd.paste(dices[0],box)
        if diceNumber==2:
            nimdd.paste(dices[1],box)
        if diceNumber==3:
            nimdd.paste(dices[2],box)
        if diceNumber==4:
            nimdd.paste(dices[3],box)
        if diceNumber==5:
            nimdd.paste(dices[4],box)
        if diceNumber==6:
            nimdd.paste(dices[5],box)
        os.system('clear')
        print x,y
        print (img.width,img.height)
        print(str((y+1)*100/img.height)+"%")
        total+=1

nimdd.show()
nimdd.save("./dicesImage","JPEG")
print total

